# **Z_test**

#Scenario :
Bombay hospitality Ltd. operates a franchise model for producing exotic Norwegian dinners throughout New England. The operating cost for a franchise in a week (W) is given by the equation W = $1,000 + $5X, where X represents the number of units produced in a week. Recent feedback from restaurant owners suggests that this cost model may no longer be accurate, as their observed weekly operating costs are higher.

Objective:
To investigate the restaurant owners' claim about the increase in weekly operating costs using hypothesis testing.

Data Provided:
•	The theoretical weekly operating cost model: W = $1,000 + $5X
•	Sample of 25 restaurants with a mean weekly cost of Rs. 3,050
•	Number of units produced in a week (X) follows a normal distribution with a mean (μ) of 600 units and a standard deviation (σ) of 25 units

# Task 1: State the Hypothesis Statement

In [1]:
##hypothesis statement
##theoretical model for weekly operating cost: W=1000+5X
##null hypothesis:the actual weekly operating cost is equal or less than theoretical model
              ##h0: actual mean weekly operating cost less than theoretical model operating cost
              ##h0: actual mean operating cost<=1000+5X
##alternate hypothesis:the actual weekly opaerating cost is highere than theoretical model
             ##h1: actual mean operating cost>1000+5X
             

In [2]:
import numpy as np
import scipy.stats as stats

##h0: actual mean operating cost<=1000+5X
##h1: actual mean operating cost>1000+5X

# Task 2: Calculate test statistic

In [3]:
##now we are going to calculate TEST STATISTIC T


In [4]:
x_bar=3050 ##sample mean weekly cost
##theoretical_mean = 1000+5*600=4000
theoretical_mean=4000
n=25 ##sample size
std_dev_units=25 ##standard deviation of units produced
std_dev_cost= 5*25 ## cost per unit* std_dev_units = stanfdard deviation of weekly operating cost


In [5]:
t_stats=(x_bar - theoretical_mean)/(std_dev_cost/np.sqrt(n)) 
t_stats

-38.0

# Task 3 : Determine Critical Value

In [6]:
##here we are doing a one_tailores z test
##now we are going to find critical value
##we give alpha=0.05

In [7]:
alpha=0.05

critical_value=stats.norm.ppf(1-alpha)
critical_value

1.6448536269514722

# Task 4: Make a decision

In [8]:
print(f"t stats- {t_stats}" )
print(f"critical value- {critical_value}")

t stats- -38.0
critical value- 1.6448536269514722


In [9]:
##here t stats is less than critical value
## so we fail to reject null hypothesis
##h0: actual mean weekly operating cost less than theoretical model operating cost


# 5. Conclusion


#Based on the decision, there is strong evidence to support
the restaurant owners' claim that the weekly operating costs
are higher than the model suggests.


# **Chisquare Test**



```
# Scenario:
Mizzare Corporation has collected data on customer
satisfaction levels for two types of smart home devices:
Smart Thermostats and Smart Lights. They want to determine
if there's a significant association between the type of
device purchased and the customer's satisfaction level.
```



```
# Objective:

To use the Chi-Square test for independence to determine if
there's a significant association between the type of smart
home device purchased (Smart Thermostats vs. Smart Lights)
and the customer satisfaction level.
```



In [10]:
import numpy as np
from scipy.stats import chi2

# 1.State the Hypotheses

In [11]:
#Stating the Hypotheses:
#H0:- There is no association between the type of device purchased and customer satisfaction.
#H1:- There is an association between the type of device purchased and customer satisfaction.
H0="There is no association between the type of device purchased and customer satisfaction."
H1="There is an association between the type of device purchased and customer satisfaction."

In [12]:
# observed values
observed = np.array([[50, 70], 
                     [80, 100], 
                     [60, 90], 
                     [30, 50], 
                     [20, 50]])
observed

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

In [13]:
# expected values calculation
row_totals=observed.sum(axis=1)
col_totals=observed.sum(axis=0)
total=observed.sum()

In [14]:
row_totals

array([120, 180, 150,  80,  70])

In [15]:
col_totals

array([240, 360])

In [16]:
total

600

In [17]:
expected = np.outer(row_totals, col_totals) / total
expected

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [18]:
observed

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

# 2. Compute chi-square statistic

In [19]:

chi_square_stat = ((observed - expected)**2 / expected).sum()
chi_square_stat

5.638227513227513

# 3. Determine critical value

In [20]:
observed.shape[1]


2

In [21]:
observed.shape[0]

5

In [22]:
# degree of freedom - (no.of rows-1) * (no.of columns-1)
df= (observed.shape[0] - 1) * (observed.shape[1] - 1)

In [23]:
df

4

In [24]:
#critical value for alpha= 0.05
alpha = 0.05
critical_value = chi2.ppf(1-alpha,df)

In [25]:
critical_value

9.487729036781154

# 4.Make a decision

In [26]:
print(f" the critical value is :{critical_value} is greater than chi_square value :{chi_square_stat}")

 the critical value is :9.487729036781154 is greater than chi_square value :5.638227513227513


In [27]:
# Decision
# if chi_square stats is greater than critical value : reject the null hypothesis else accept the null hypothesis
# so our decision is to accept null hypothesis
# H0:- "There is no association between device purchased and customer satisfaction" -Accepted

In [28]:
decision=print(f"accepted-{H0}")

accepted-There is no association between the type of device purchased and customer satisfaction.
